#!/bin/sh

if sassc -h >/dev/null
# http://libsass.org/
then sassc -g -o playground.css playground.scss
# http://sass-lang.com/
else sass playground.scss playground.css
fi

# http://coffeescript.org/
coffee --compile playground.coffee

cat jquery-1.10.2.min.js underscore-min.js backbone-min.js backbone.localStorage-min.js lispy/lispy.js playground.js coffee-script.js > concatenated-scripts.js

